# Generated by Django 5.1.7 on 2025-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('bpm', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('voice_pitch', models.FloatField(help_text='Pitch in Hz')),
                ('shaking', models.FloatField(help_text='Movement intensity')),
                ('label', models.CharField(blank=True, choices=[('truth', 'Truth'), ('lie', 'Lie')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
